### ISSUE TITLE
Show error for two identical testsuite and testcase names

### ISSUE THREAD

**Issue by dakaa16** [openmainframeproject/cobol-check#217]
Having 2 or more testsuites or testcases with the same name might lead to errors or unexpected behavior. However, the errors does not pertain to the root cause; identical testsuite or testcase names.
An error should be thrown if:
- Two or more testsuites exists with identical names for the same source program
- Two or more testcases exists with identical names within a testsuite

**Comment by literalEval** [comment]
@dakaa16 I am interested in working on this issue :)

**Comment by Rune-Christensen** [comment]
@literalEval Yes, that could be a solution.
Just to make sure you didn't misunderstand the issue. 
It is fine for two testcases to have the same content, it is just the name that needs to be unique. 
This also applies to testsuites.

**Comment by literalEval** [comment]
Thanks

**Comment by literalEval** [comment]
@Rune-Christensen since I am new to this codebase, can you please refer the file that needs the change?
From what I understood in the codebase till now, it should be [TestSuiteParser.java file](https://github.com/openmainframeproject/cobol-check/blob/Developer/src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/TestSuiteParser.java). Am I correct?
