### ISSUE TITLE
File Statement need FIX

### ISSUE THREAD

**Issue by samdion1994** [openmainframeproject/cobol-check#333]
Hi @Rune-Christensen,

**I happened to see this error the other day. Care to share your thoughts?**

        String s1 = "       WORKING-STORAGE SECTION.";
        String s2 = "       PROCEDURE DIVISION.";
        String s3 = "       851-PLACEHOLDER.";
        String s4 = "           READ THIS-FILE INTO THAT-VARIABLE";
        String s5 = "               AT END";
        String s6 = "                 DISPLAY ALLO"; 
        String s7 = "           END-READ";  

**ends up giving me** 

![image](https://github.com/openmainframeproject/cobol-check/assets/88783494/0d4abaa9-5637-4d3a-b380-de70695f7b0c)

"   *        READ THIS-FILE INTO THAT-VARIABLE";
"   *            AT END";
"                 DISPLAY ALLO"; 
"           END-READ";  

I could comment the whole thing but then how would we test the AT END.

I can fix it, just not sure how to go about it thanks!

**Comment by Rune-Christensen** [comment]
Hi @samdion1994 

There is a lot of work not yet done, regarding file management.
This is one of the situations, that cannot yet be managed by COBOL Check.
We usually recommend our developers, to isolate the code that needs to be mocked, inside a new section or paragraph, and then mock the section.

In this situation that is not enough, because the compile will fail.

Atm. I suggest commenting the entire read - end-read statement.
Regarding testing the at end statement, I currently have no good answer to that.

**Comment by samdion1994** [comment]
Thanks for the input :)
